# Tags: 3.1-focal
FROM dotnet/runtime-deps:3.1-focal
FROM dotnet/runtime-deps:3.1.21-focal
FROM dotnet/runtime-deps:5.0.12-focal-amd64
FROM dotnet/runtime-deps:5.0-focal-amd64
FROM dotnet/runtime-deps:6.0-focal-amd64
FROM dotnet/runtime-deps:6.0.0-focal-amd64
