# Tags: 3.1-buster-slim
FROM dotnet/runtime-deps:3.1-buster-slim
FROM dotnet/runtime-deps:3.1.21-buster-slim
FROM dotnet/runtime-deps:5.0-buster-slim-amd64
FROM dotnet/runtime-deps:5.0.12-buster-slim-amd64
