# Tags: 3.1-bullseye-slim-arm64v8, 3.1.21-bullseye-slim-arm64v8, 5.0-bullseye-slim-arm64v8, 5.0.12-bullseye-slim-arm64v8, 6.0-bullseye-slim-arm64v8, 6.0.0-bullseye-slim-arm64v8
FROM mcr.microsoft.com/dotnet/runtime-deps:3.1-bullseye-slim-arm64v8
FROM mcr.microsoft.com/dotnet/runtime-deps:3.1.21-bullseye-slim-arm64v8
FROM mcr.microsoft.com/dotnet/runtime-deps:5.0-bullseye-slim-arm64v8
FROM mcr.microsoft.com/dotnet/runtime-deps:5.0.12-bullseye-slim-arm64v8
FROM mcr.microsoft.com/dotnet/runtime-deps:6.0-bullseye-slim-arm64v8
FROM mcr.microsoft.com/dotnet/runtime-deps:6.0.0-bullseye-slim-arm64v8
