# Tags: 3.1-alpine3.13-arm64v8
FROM dotnet/runtime-deps:3.1-alpine3.13-arm64v8
FROM dotnet/runtime-deps:5.0-alpine3.13-arm64v8
FROM dotnet/runtime-deps:3.1.21-alpine3.13-arm64v8
FROM dotnet/runtime-deps:5.0.12-alpine3.13-arm64v8
