# Tags: 5.0-alpine3.14-arm32v7, 5.0-alpine-arm32v7, 5.0.12-alpine3.14-arm32v7, 6.0-alpine-arm32v7, 6.0-alpine3.14-arm32v7, 6.0.0-alpine3.14-arm32v7
FROM mcr.microsoft.com/dotnet/runtime-deps:5.0-alpine3.14-arm32v7
FROM mcr.microsoft.com/dotnet/runtime-deps:5.0-alpine-arm32v7
FROM mcr.microsoft.com/dotnet/runtime-deps:5.0.12-alpine3.14-arm32v7
FROM mcr.microsoft.com/dotnet/runtime-deps:6.0-alpine-arm32v7
FROM mcr.microsoft.com/dotnet/runtime-deps:6.0-alpine3.14-arm32v7
FROM mcr.microsoft.com/dotnet/runtime-deps:6.0.0-alpine3.14-arm32v7
