# Tags: 3.1-bullseye-slim-arm32v7
FROM dotnet/runtime-deps:3.1-bullseye-slim-arm32v7
FROM dotnet/runtime-deps:3.1.21-bullseye-slim-arm32v7
FROM dotnet/runtime-deps:5.0-bullseye-slim-arm32v7
FROM dotnet/runtime-deps:5.0.12-bullseye-slim-arm32v7
FROM dotnet/runtime-deps:6.0.0-bullseye-slim-arm32v7
FROM dotnet/runtime-deps:6.0-bullseye-slim-arm32v7
