# Tags: 3.1-alpine3.13, 3.1.21-alpine3.13, 5.0-alpine3.13-amd64, 5.0.12-alpine3.13-amd64
FROM mcr.microsoft.com/dotnet/runtime-deps:3.1-alpine3.13
FROM mcr.microsoft.com/dotnet/runtime-deps:3.1.21-alpine3.13
FROM mcr.microsoft.com/dotnet/runtime-deps:5.0-alpine3.13-amd64
FROM mcr.microsoft.com/dotnet/runtime-deps:5.0.12-alpine3.13-amd64
