# Tags: 3.1-buster-slim, 3.1.21-buster-slim, 5.0-buster-slim-amd64, 5.0.12-buster-slim-amd64
FROM mcr.microsoft.com/dotnet/runtime-deps:3.1-buster-slim
FROM mcr.microsoft.com/dotnet/runtime-deps:3.1.21-buster-slim
FROM mcr.microsoft.com/dotnet/runtime-deps:5.0-buster-slim-amd64
FROM mcr.microsoft.com/dotnet/runtime-deps:5.0.12-buster-slim-amd64
