# Tags: 3.1-alpine3.14
FROM dotnet/runtime-deps:3.1-alpine3.14
FROM dotnet/runtime-deps:3.1-alpine
FROM dotnet/runtime-deps:3.1.21-alpine3.14
FROM dotnet/runtime-deps:5.0-alpine3.14-amd64
FROM dotnet/runtime-deps:5.0-alpine-amd64
FROM dotnet/runtime-deps:5.0.12-alpine3.14-amd64
FROM dotnet/runtime-deps:6.0-alpine-amd64
FROM dotnet/runtime-deps:6.0-alpine3.14-amd64
FROM dotnet/runtime-deps:6.0.0-alpine3.14-amd64
